version: "3"
services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - 8080:80
    networks:
      - back
    depends_on:
      - db
  db:
    image: mariadb
    networks:
      - back
    ports:
     - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=chat-test
  adminer:
    image: adminer
    restart: always
    networks:
      - back
    ports:
      - 8081:8080

volumes:
  h2Data:

networks:
  back: