server:
  port: 80
  address: 0.0.0.0

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://db:3306/chat-test
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    root: WARN